### PR TITLE
Fixing an issue where the rule ordering was always being reset once y…

### PR DESCRIPTION
**Pull request by urfolomeus**
…ou submited the Manage Rules form.

TL;DR we were searching for a string ID in an array on integer IDs  >.<

### CODE REVIEW

**Comment by paulanthonywilson** [comment]
Hah. :+1:

**Comment by Tr4pSt3R** [comment]
:+1:

**Comment by urfolomeus** [comment]
Thanks @paulanthonywilson and @Tr4pSt3R :)

**Comment by asmega** [comment]
where does `rule_ids` come from on line 44?

**Comment by urfolomeus** [comment]
@asmega from the `has_many :rules, through: :applied_feed_rules` association.

**Comment by asmega** [comment]
ah, thanks!

**Pull request merged**
