### PR TITLE
Adding a special rule for prepending canonical links to feed items

### PR DESCRIPTION
**Pull request by mconnell**
Adds an option to feeds which enables a canonical link HTML tag to be included within each item of content in a feed. It is enabled by default.

### CODE REVIEW

**Comment by asmega** [comment]
:+1:  What happens when the order value is the same (e.g. 99)?

**Comment by urfolomeus** [comment]
If rules have the same ordering they will be run in the order in which the database returns them. What we are saying by giving two or more rules the same ordering is that those rules have no precedence over one another.

**Comment by asmega** [comment]
@urfolomeus Thanks, good to know

**Comment by benbarnett** [comment]
:+1:

**Pull request merged**
